name: Deploy to GitHub Pages

on:
  push:
    branches:
      - sitio-web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          external_repository: LMBALMIS/programacioniesbalmis.github.io

      - name: Install dependencies
        run: npm install  # o cualquier otro comando para construir tu sitio

      - name: Build and deploy
        run: |
          npm run build  # o el comando necesario para construir tu sitio
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout gh-pages  # Cambia a la rama gh-pages (o master, según tu configuración)
          git pull origin gh-pages
          cp -r build/* .  # Copia los archivos construidos a la raíz
          git add .
          git commit -m "Deployed website" || true
          git push origin gh-pages

